name: LiveChatTranslate
version: '${project.version}'
main: net.blockhost.livechattranslate.LiveChatTranslate
api-version: 1.19
authors: [ qbasty ]
description: Translate chat messages live to all the languages around the world!
website: https://blockhost.net
